//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhHoc
    {
        public string MaLop { get; set; }
        public System.DateTime NgayThamGia { get; set; }
        public System.TimeSpan TGBD { get; set; }
        public Nullable<System.TimeSpan> TGKT { get; set; }
        public string NoiDung { get; set; }
        public string MaGV { get; set; }
        public string PhongHoc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
