//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaHocSinhNam
    {
        public string MaHS { get; set; }
        public string NamHoc { get; set; }
        public string TheLuc { get; set; }
        public string Ngonngu { get; set; }
        public string NhanThuc { get; set; }
        public string TinhCamQHXH { get; set; }
        public string ThamMy { get; set; }
        public string DanhGiaChung { get; set; }
        public string DanhHieu { get; set; }
        public string MaGV { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
