//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaHocSinhTuan
    {
        public string MaHS { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public string HoatDong { get; set; }
        public string SucKhoe { get; set; }
        public string HocTap { get; set; }
        public string DanhGiaChung { get; set; }
        public string MucDoc { get; set; }
        public string MaGV { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
