//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.ChuongTrinhHocs = new HashSet<ChuongTrinhHoc>();
            this.DanhGiaHocSinhNams = new HashSet<DanhGiaHocSinhNam>();
            this.DanhGiaHocSinhTuans = new HashSet<DanhGiaHocSinhTuan>();
            this.Lops = new HashSet<Lop>();
            this.Lops1 = new HashSet<Lop>();
        }
    
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string BoMon { get; set; }
        public string Password { get; set; }
        public byte[] Hinh { get; set; }
        public Nullable<int> Quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuongTrinhHoc> ChuongTrinhHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaHocSinhNam> DanhGiaHocSinhNams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaHocSinhTuan> DanhGiaHocSinhTuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lops1 { get; set; }
    }
}
