//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKHHTMNEntities : DbContext
    {
        public QLKHHTMNEntities()
            : base("name=QLKHHTMNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuongTrinhHoc> ChuongTrinhHocs { get; set; }
        public virtual DbSet<DanhGiaHocSinhNam> DanhGiaHocSinhNams { get; set; }
        public virtual DbSet<DanhGiaHocSinhTuan> DanhGiaHocSinhTuans { get; set; }
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<HocSinh> HocSinhs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<PhieuKhamSucKhoe> PhieuKhamSucKhoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
