//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKhamSucKhoe
    {
        public string MaHS { get; set; }
        public System.DateTime NgayKham { get; set; }
        public Nullable<double> CanNang { get; set; }
        public Nullable<double> ChieuCao { get; set; }
        public string TaiMuiHong { get; set; }
        public string Mat { get; set; }
        public string KL { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
